from SproutGame.resources.constants import CANVAS_SIZE
###GUI###
TEXT_FONT = ("Helvetica", 12)
BACKGROUND_COLOR = "#f2f2f2"
ERROR_TEXT_COLOR = "#FF0000"
MAIN_MENU_TITLE = "Main Menu"
MAIN_MENU_GEOMETRY = "300x340"
NUMBER_PLAYERS_LABEL = "Enter number of players:"
NUMBER_SPOTS_LABEL = "Enter number of spots:"
TIME_BASED_GAME_TEXT = "Time-based game"
OK_BUTTON_TEXT = "Submit"
PLAYER_INFO_TITLE ="Player Info" 
NAME_NOT_SET_ERROR_TEXT = "Enter the name"
COLOR_NOT_SET_ERROR_TEXT = "Choose the color"
PLAYER_NUMBER_NOT_SET_ERROR_TEXT = "Enter number of players"
SPOT_NUMBER_NOT_SET_ERROR_TEXT = "Enter number of spots"
NOT_ENOUGH_PLAYERS_ERROR_TEXT = "Minimum number of players is 2"
NOT_ENOUGH_SPOTS_ERROR_TEXT = "Minimum number of spots is 1"
TOO_MANY_PLAYERS_ERROR_TEXT = "Maximum number of players is 10"
TOO_MANY_SPOTS_ERROR_TEXT = "Maximum number of spots is 8"
MAIN_GAME_GEOMETRY = f"{CANVAS_SIZE}x{CANVAS_SIZE + 40}"
MAIN_MENU_BUTTON_TEXT = "Main Menu"
CANVAS_BACKGROUND_COLOR = "white"
MOVE_NOT_POSSIBLE_GAME_OVER = "You cant move, game overed"
GAME_OVER_TITLE = "Game over"
STEP_LOADING_LABEL = "Step in progress..."